/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phaseIII;

import javax.swing.JOptionPane;
import static phaseIII.Login.city;
import static phaseIII.Login.state;

/**
 *
 * @author shuangliang
 */
public class Add_poi extends javax.swing.JPanel {
    private int flag1 =0;
    private int flag2=0;
    private int flag3=0;
    /**
     * Creates new form Add_poi
     */
    public TestFrame frame;
    public Add_poi(TestFrame f) {
        initComponents();
        frame = f;
        flag3=1;
        CCity.addItem("Not Selected");
        CState.addItem("Not Selected");
         for (int i=0;i<21;i++){
        CCity.addItem(city[i]);
        int isExisted =0;
        for (int j=0;j<i;j++){
            if(state[j].equals(state[i])){
                 isExisted =1;
            }
        }
        if(isExisted==0){
            CState.addItem(state[i]);
        }
        flag3=0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CCity = new javax.swing.JComboBox<>();
        CState = new javax.swing.JComboBox<>();
        zipCode = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        poiLocName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane7 = new javax.swing.JDesktopPane();
        jDesktopPane9 = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("State:");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Zip code:");

        CCity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CCityItemStateChanged(evt);
            }
        });

        CState.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CStateItemStateChanged(evt);
            }
        });

        zipCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        zipCode.setPreferredSize(new java.awt.Dimension(200, 20));

        backButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        backButton.setText("Back");
        backButton.setToolTipText("");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.setToolTipText("");
        submitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Add a new location");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("POI location name:");

        poiLocName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        poiLocName.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("City:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poiLocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(199, 199, 199))
            .addComponent(jDesktopPane7)
            .addComponent(jDesktopPane9)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poiLocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jDesktopPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CCityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CCityItemStateChanged
     if(flag3!=1){
        if(flag2!=1){
        flag1=1;
        int tmp = CCity.getSelectedIndex();
        if(tmp!=-1){ 
        for (int i=0;i<21;i++){
            if (CCity.getSelectedItem().equals(city[i])){
                CState.setSelectedItem(state[i]);
            }
        }
           if(CCity.getSelectedItem().equals("Not Selected")){
            CState.setSelectedItem("Not Selected");
        }
        }
        flag1=0;
        }
     }
    }//GEN-LAST:event_CCityItemStateChanged

    private void CStateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CStateItemStateChanged
      if(flag3!=1){
        if(flag1 !=1){
      flag2=1;
      CCity.removeAllItems();
       if(!CState.getSelectedItem().equals("Not Selected")){
        for (int i=0;i<21;i++){
            if (CState.getSelectedItem().equals(state[i])){
                CCity.addItem(city[i]);
            }
        }
      }else{
            CCity.addItem("Not Selected");
         for (int i=0;i<21;i++){
        CCity.addItem(city[i]);
         }
       }
     flag2=0;
      }
      }
    }//GEN-LAST:event_CStateItemStateChanged
    private void clean_up(){
        poiLocName.setText("");
        zipCode.setText("");
         flag3=1;
        CCity.removeAllItems();
        CState.removeAllItems();
        CCity.addItem("Not Selected");
        CState.addItem("Not Selected");
          for (int i=0;i<21;i++){
        CCity.addItem(city[i]);
        int isExisted =0;
        for (int j=0;j<i;j++){
            if(state[j].equals(state[i])){
                 isExisted =1;
            }
        }
        if(isExisted==0){
            CState.addItem(state[i]);
        }
        }
        flag3=0;
    }
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String poiLocName_input= poiLocName.getText();
        String city_input = CCity.getSelectedItem().toString();
        String state_input=CState.getSelectedItem().toString();
        String zipcode_input = zipCode.getText();
        POI new_poi;
        if(city_input.equals("Not Selected")||state_input.equals("Not Selected")){
             JOptionPane.showMessageDialog(null, "City or State not selected! Please select one!"); 
             this.clean_up();
        }else if(zipcode_input.length()!=5){
            JOptionPane.showMessageDialog(null, "The number of digits of zip code must be 5! Please try again!");
            this.clean_up();
        }else{
        new_poi = new POI(poiLocName_input,null,null,zipcode_input,city_input,state_input);
        int feedback = DB_test.Add_POI(new_poi);
        switch(feedback){
            case 0:  JOptionPane.showMessageDialog(null, "POI Location Name is already existed! Please"
                    + " choose another name."); 
                     break;
            case 1: JOptionPane.showMessageDialog(null, "Congratulations! POI has been added successfully!"); 
                     break;
        }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
      
         frame.getContentPane().removeAll();
         frame.getContentPane().invalidate();
         frame.getContentPane().add(new Add_data_pt(frame));
         frame.getContentPane().revalidate();
         frame.pack();  
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CCity;
    private javax.swing.JComboBox<String> CState;
    private javax.swing.JButton backButton;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JDesktopPane jDesktopPane9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField poiLocName;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField zipCode;
    // End of variables declaration//GEN-END:variables
}
