/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phaseIII;

/**
 *
 * @author shuangliang
 */
public class City_Off_Func extends javax.swing.JPanel {

    /**
     * Creates new form City_Off_Func
     */
    public TestFrame frame;
    public City_Off_Func(TestFrame f) {
        initComponents();
         frame = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FSpoiLabel = new javax.swing.JLabel();
        poiRepLabel = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane8 = new javax.swing.JDesktopPane();
        jDesktopPane10 = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 400));

        FSpoiLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        FSpoiLabel.setForeground(new java.awt.Color(102, 102, 102));
        FSpoiLabel.setText("<html><u>Filter/Search POI</u></html>");
        FSpoiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FSpoiLabelMouseClicked(evt);
            }
        });

        poiRepLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        poiRepLabel.setForeground(new java.awt.Color(102, 102, 102));
        poiRepLabel.setText("<html><u>POI Report</u></html>");
        poiRepLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poiRepLabelMouseClicked(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        LogoutButton.setText("Log out");
        LogoutButton.setToolTipText("");
        LogoutButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Choose Functionality");

        jDesktopPane8.setSize(600,25);

        jDesktopPane10.setSize(600,25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane8)
            .addComponent(jDesktopPane10)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(poiRepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(FSpoiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(136, 136, 136))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(380, 380, 380)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(120, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(FSpoiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(poiRepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jDesktopPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FSpoiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FSpoiLabelMouseClicked
         frame.getContentPane().removeAll();
         frame.getContentPane().invalidate();
         frame.getContentPane().add(new FS_POI(frame));
         frame.getContentPane().revalidate();
         frame.pack();
    }//GEN-LAST:event_FSpoiLabelMouseClicked

    private void poiRepLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poiRepLabelMouseClicked
         Object[][] result = DB_test.POI_Report_View(); 
         frame.getContentPane().removeAll();
         frame.getContentPane().invalidate();
         frame.getContentPane().add(new POI_Report(frame,result));
         frame.getContentPane().revalidate();
         frame.pack();
    }//GEN-LAST:event_poiRepLabelMouseClicked

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        frame.getContentPane().removeAll();
        frame.getContentPane().invalidate();
        frame.getContentPane().add(new Login(frame));
        frame.getContentPane().revalidate();
        frame.pack();
    }//GEN-LAST:event_LogoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FSpoiLabel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JDesktopPane jDesktopPane10;
    private javax.swing.JDesktopPane jDesktopPane8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel poiRepLabel;
    // End of variables declaration//GEN-END:variables
}
