/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phaseIII;
/**
 *
 * @author shuangliang
 */
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.*;
import static phaseIII.DB_test.conn;

public class Login extends javax.swing.JPanel {
    public static String [] city = new String[21];
     public static String [] state = new String[21];  
 
    public TestFrame frame;
    public Login(TestFrame f) {
         try{
        csvreader();
      }catch(FileNotFoundException e){
           System.out.println("File not found!");
      }    
        initComponents(); 
        DB_test.conn_and_test();
        insertcitystate();
        insertdatatype();
        frame = f;
    }
    
    public void insertcitystate(){
        for(int i=0;i<21;i++){
            try{
            PreparedStatement pstmt = conn.prepareStatement("INSERT INTO CityState values(?,?)");
            pstmt.setString(1,city[i]);
            pstmt.setString(2,state[i]);
            pstmt.executeUpdate();
              }catch(SQLException se){
        }   
        }
    }
       public void insertdatatype(){
            try{
            PreparedStatement pstmt = conn.prepareStatement("INSERT INTO DataType values(?)");
            pstmt.setString(1,"Mold");
            pstmt.executeUpdate();
            PreparedStatement pstmt2 = conn.prepareStatement("INSERT INTO DataType values(?)");
            pstmt2.setString(1,"Air Quality");
            pstmt2.executeUpdate();
              }catch(SQLException se){
        }   
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        loginbutton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(450, 430));

        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passwordField.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Username");

        usernameField.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        usernameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usernameField.setPreferredSize(new java.awt.Dimension(200, 20));

        loginbutton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        loginbutton.setText("Login");
        loginbutton.setToolTipText("");
        loginbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        registerButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        registerButton.setText("Register");
        registerButton.setToolTipText("");
        registerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phaseIII/GTYellowJacket.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void csvreader() throws FileNotFoundException{
        String csvFile = "citystate.csv";
        String line = "";
        String cvsSplitBy = ",";
        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
            int i=-1;
            while ((line = br.readLine()) != null) {
                if (i!=-1) {
                    String[] citystate = line.split(cvsSplitBy);
                    city[i]=citystate[1];
                    state[i]=citystate[2];
                }
                i++;
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
        
       // test code
     /*   for (int j=0;j<21;j++) {
            System.out.println("city is " + city[j]);
            System.out.println("state is "+state[j]);
        }  */
}
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

         frame.getContentPane().removeAll();
         frame.getContentPane().invalidate();
         frame.getContentPane().add(new New_U_Reg(frame));
         frame.getContentPane().revalidate();
         frame.pack();
         
    }//GEN-LAST:event_registerButtonActionPerformed
    private void change_panel(int i){
        if(i==1){
         frame.getContentPane().removeAll();
         frame.getContentPane().invalidate();
         frame.getContentPane().add(new Add_data_pt(frame));
         frame.getContentPane().revalidate();
         frame.pack();
        }
        else if(i==2){
         frame.getContentPane().removeAll();
         frame.getContentPane().invalidate();
         frame.getContentPane().add(new City_Off_Func(frame));
         frame.getContentPane().revalidate();
         frame.pack();
        }
        else if(i==3){
         frame.getContentPane().removeAll();
         frame.getContentPane().invalidate();
         frame.getContentPane().add(new Admin_Func(frame));
         frame.getContentPane().revalidate();
         frame.pack();
        }       
    }
    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        //FIRST:event_loginbuttonActionPerformed
        if(usernameField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Please enter a nonempty username");
            usernameField.setText("");
            passwordField.setText("");
        }
        else if(passwordField.getPassword().length <= 8 ) {
           JOptionPane.showMessageDialog(null, "Please enter password that "
                   + "is longer than 8 digits");
           passwordField.setText("");
           usernameField.setText("");
       }else{
            String email = usernameField.getText();
            String password = String.valueOf(passwordField.getPassword());
            int feedback = DB_test.login(email,password);
            System.out.println("Feedback is "+feedback);
            switch (feedback){
                case 0:  JOptionPane.showMessageDialog(null, "User Not Existed. Please try again!");
                         usernameField.setText("");
                         passwordField.setText("");
                         break;
                case 1:   JOptionPane.showMessageDialog(null, "Login Successful!");
                          change_panel(1);
                          break;
                case 2:   JOptionPane.showMessageDialog(null, "Login Successful!");
                          change_panel(2);
                          break;
                case 3:   JOptionPane.showMessageDialog(null, "Login Successful!");
                          change_panel(3);
                          break;
                case 11:  JOptionPane.showMessageDialog(null, "Incorrect Username.");
                          usernameField.setText("");
                          passwordField.setText("");
                          break;
                case 10:   JOptionPane.showMessageDialog(null, "Incorrect Password.");
                           usernameField.setText("");
                           passwordField.setText("");
                           break;
                case 20: JOptionPane.showMessageDialog(null, "Your registration has not been approved. Please contact administrator!");
                         usernameField.setText("");
                         passwordField.setText("");
                         break;
                case 99: JOptionPane.showMessageDialog(null, "Log in failed!");
                         usernameField.setText("");
                         passwordField.setText("");
                         break;
            }
       }
    }//GEN-LAST:event_loginbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
