/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phaseIII;
import java.io.FileNotFoundException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import phaseIII.DB_test;
import static phaseIII.Login.city;
import static phaseIII.Login.state;
/**
 *
 * @author shuangliang
 */
public class New_U_Reg extends javax.swing.JPanel {

    /**
     * Creates new form New_U_Reg
     */
    public TestFrame frame;
    private int flag1 =0;
    private int flag2=0;
    private int flag3=0;
    public New_U_Reg(TestFrame f) {

        initComponents();
        flag3=1;
        CCity.addItem("Not Selected");
        CState.addItem("Not Selected");
         for (int i=0;i<21;i++){
        CCity.addItem(city[i]);
        int isExisted =0;
        for (int j=0;j<i;j++){
            if(state[j].equals(state[i])){
                 isExisted =1;
            }
        }
        if(isExisted==0){
            CState.addItem(state[i]);
        }
        }
         flag3=0;
        frame = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cUsertype = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CState = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        tTitle = new javax.swing.JTextField();
        CCity = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        tPassword = new javax.swing.JPasswordField();
        tCPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 550));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Confirm Password");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Fill out this form if you choose city officials");

        jButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("User Type");

        cUsertype.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cUsertype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "City Official", "City Scientist" }));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("New User Registration");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 150));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("City:");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setText("State:");
        jLabel11.setToolTipText("");

        CState.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        CState.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CStateItemStateChanged(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setText("Title:");
        jLabel12.setToolTipText("");

        tTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tTitle.setPreferredSize(new java.awt.Dimension(150, 20));

        CCity.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        CCity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CCityItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Email Address");

        tEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tEmail.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Username");

        tUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tUsername.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Password");

        jDesktopPane3.setLayout(null);

        jDesktopPane5.setLayout(null);

        tPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tPassword.setPreferredSize(new java.awt.Dimension(200, 20));
        tPassword.setSize(new java.awt.Dimension(200, 20));

        tCPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tCPassword.setPreferredSize(new java.awt.Dimension(200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane3)
            .addComponent(jDesktopPane5)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cUsertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(185, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cUsertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
  
    public void csvreader() throws FileNotFoundException{
        String csvFile = "citystate.csv";
        String line = "";
        String cvsSplitBy = ",";
        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
            int i=-1;
            while ((line = br.readLine()) != null) {
                if (i!=-1) {
                    String[] citystate = line.split(cvsSplitBy);
                    city[i]=citystate[1];
                    state[i]=citystate[2];
                }
                i++;
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
       // test code
     /*   for (int j=0;j<21;j++) {
            System.out.println("city is " + city[j]);
            System.out.println("state is "+state[j]);
        }  */
}
       
    private void clean_up(){
        tPassword.setText("");
        tCPassword.setText("");
        tEmail.setText("");
        tTitle.setText("");
        tUsername.setText("");
        flag3=1;
        CCity.removeAllItems();
        CState.removeAllItems();
        CCity.addItem("Not Selected");
        CState.addItem("Not Selected");
          for (int i=0;i<21;i++){
        CCity.addItem(city[i]);
        int isExisted =0;
        for (int j=0;j<i;j++){
            if(state[j].equals(state[i])){
                 isExisted =1;
            }
        }
        if(isExisted==0){
            CState.addItem(state[i]);
        }
        }
          flag3=0;
        cUsertype.setSelectedIndex(0);     
    }
    
    private void back_to_login(){
         frame.getContentPane().removeAll();
         frame.getContentPane().invalidate();
         frame.getContentPane().add(new Login(frame));
         frame.getContentPane().revalidate();
         frame.pack();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String new_user_password = new String(tPassword.getPassword());
      if((tPassword.getPassword()).equals(tCPassword.getPassword())){
         JOptionPane.showMessageDialog(null, "Password and confirm password don't match. Please try again!");
         this.clean_up();
     }else if(tEmail.getText().indexOf('@')== -1){
         JOptionPane.showMessageDialog(null, "Email address not valid. Please try again!");
         this.clean_up();
         
     }else if(8>tPassword.getPassword().length){
         JOptionPane.showMessageDialog(null, "Please enter password that "
                 + "is longer than 8 digits.");
         this.clean_up();
     }
     else if(cUsertype.getSelectedItem().equals("City Official")){
         CityOfficial new_cityofficial = new CityOfficial(tUsername.getText(),tEmail.getText(),new_user_password,
                 "City Official",tTitle.getText(),null,CCity.getSelectedItem().toString(),CState.getSelectedItem().toString());
          System.out.println(new_user_password);
         int feedback = DB_test.Register_CityOfficial(new_cityofficial);
         if (feedback == 2){
             JOptionPane.showMessageDialog(null, "Congratulations! Your registraion has completed!");
             this.back_to_login();
         }
         else if(feedback == 1){
             JOptionPane.showMessageDialog(null, "Email Address Existed. Please choose another one.");
             this.clean_up();
         }
         else if(feedback == 0){
             JOptionPane.showMessageDialog(null, "Username Existed.Please choose another one.");
             this.clean_up();
         }
         else if(feedback == 10){
              JOptionPane.showMessageDialog(null, "Registration failed!");
             this.clean_up();
         }
         
     }else if(cUsertype.getSelectedItem().equals("City Scientist")){
         String new_user_username = tUsername.getText();
         System.out.println(new_user_password);
         String new_user_email = tEmail.getText();
         User new_user = new User(new_user_username,new_user_email,new_user_password
                 ,"City Scientist");
         int feedback = DB_test.Register_User(new_user);
         if(feedback == 2){
             JOptionPane.showMessageDialog(null, "Congratulations! Your registraion has completed!");
             this.back_to_login();
         }
         else if(feedback == 1){
             JOptionPane.showMessageDialog(null, "Email is already existed! Please"
                     + "choose another Email.");
             this.clean_up();
         }
         else{
             JOptionPane.showMessageDialog(null, " Username is already existed! Please"
                     + " choose another Username.");
             this.clean_up();
         }
     }else {
            JOptionPane.showMessageDialog(null, "Password and confirm password don't match. Please try again!");
            this.clean_up();
     }
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CCityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CCityItemStateChanged
        if(flag3!=1){
        if(flag2!=1){
        flag1=1;
        int tmp = CCity.getSelectedIndex();
        if(tmp!=-1){ 
        for (int i=0;i<21;i++){
            if (CCity.getSelectedItem().equals(city[i])){
                CState.setSelectedItem(state[i]);
            }
        }
        if(CCity.getSelectedItem().equals("Not Selected")){
            CState.setSelectedItem("Not Selected");
        }
        }
        flag1=0;
        }
        }
    }//GEN-LAST:event_CCityItemStateChanged

    private void CStateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CStateItemStateChanged
      if(flag3!=1){
      if(flag1 !=1){
      flag2=1;
      CCity.removeAllItems();
       if(!CState.getSelectedItem().equals("Not Selected")){
        for (int i=0;i<21;i++){
            if (CState.getSelectedItem().equals(state[i])){
                CCity.addItem(city[i]);
            }
        }
      }else{
            CCity.addItem("Not Selected");
         for (int i=0;i<21;i++){
        CCity.addItem(city[i]);
         }
      }
      flag2=0;
      }
      }
    }//GEN-LAST:event_CStateItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CCity;
    private javax.swing.JComboBox<String> CState;
    private javax.swing.JComboBox<String> cUsertype;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tCPassword;
    private javax.swing.JTextField tEmail;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tTitle;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
