/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phaseIII;

/**
 *
 * @author WYF
 */
public class Pending_City_Official_Accounts extends javax.swing.JPanel {

    /**
     * Creates new form Pending_City_Official_Accounts
     */
    public TestFrame frame;
    public myTable table;
    public Object[] column = {"Select","Username","Email","City","State","Title"};
    public Pending_City_Official_Accounts(TestFrame f, Object[][] result) {
        initComponents();
        table =  new myTable(result,column,this,new int[]{60,150,500,100});
        frame =f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();
        jDesktopPane8 = new javax.swing.JDesktopPane();
        jDesktopPane9 = new javax.swing.JDesktopPane();
        jDesktopPane10 = new javax.swing.JDesktopPane();
        jDesktopPane11 = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Pending City Official Accounts");

        backButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        backButton.setText("Back");
        backButton.setToolTipText("");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        rejectButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        rejectButton.setText("Reject");
        rejectButton.setToolTipText("");
        rejectButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        acceptButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        acceptButton.setText("Accept");
        acceptButton.setToolTipText("");
        acceptButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        jDesktopPane8.setSize(600,25);

        jDesktopPane9.setSize(600,25);
        jDesktopPane8.add(jDesktopPane9);

        jDesktopPane10.setSize(600,25);

        jDesktopPane11.setSize(600,25);
        jDesktopPane10.add(jDesktopPane11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jDesktopPane8)
            .addComponent(jDesktopPane10)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jDesktopPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
         frame.getContentPane().removeAll();
         frame.getContentPane().invalidate();
         frame.getContentPane().add(new Admin_Func(frame));
         frame.getContentPane().revalidate();
         frame.pack();
    }//GEN-LAST:event_backButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        // TODO add your handling code here:
        int[] user_selected = table.getRow(); 
        System.out.println("usernames selected" );
        String[] usernames = new String[user_selected.length];
        for(int i = 0; i<user_selected.length;i++){
            Object[] temp = table.get_row_object(user_selected[i]);        
            usernames[i] =  temp[1].toString();
            System.out.println("usernames " +usernames[i]);                     
        }
        DB_test.reject_CityOfficial(usernames);
        table.delete_row(user_selected);
    }//GEN-LAST:event_rejectButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
        int[] user_selected = table.getRow(); 
        System.out.println("usernames selected" );
        String[] usernames = new String[user_selected.length];
        for(int i = 0; i<user_selected.length;i++){
            Object[] temp = table.get_row_object(user_selected[i]);        
            usernames[i] =  temp[1].toString();
            System.out.println("usernames " +usernames[i]);                     
        }
        DB_test.accept_CityOfficial(usernames);
        table.delete_row(user_selected);
    }//GEN-LAST:event_acceptButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton backButton;
    private javax.swing.JDesktopPane jDesktopPane10;
    private javax.swing.JDesktopPane jDesktopPane11;
    private javax.swing.JDesktopPane jDesktopPane8;
    private javax.swing.JDesktopPane jDesktopPane9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton rejectButton;
    // End of variables declaration//GEN-END:variables
}
