/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phaseIII;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static phaseIII.Login.city;
import static phaseIII.Login.state;

/**
 *
 * @author shuangliang
 */
public class POI_detail extends javax.swing.JPanel {

    /**
     * Creates new form POI_detail
     */
    public TestFrame frame;
    private Object[][] dp_table =null;
    public String selected_location;
    public myTable table;
    public Object[] column = {"Data Type","Data Value","Time & date of data reading"};
    private int flag =0;
    
    public POI_detail(TestFrame f,String selected_loc) {
        initComponents();
        selected_location = selected_loc;
        frame = f;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataType = new javax.swing.JComboBox();
        startTime = new javax.swing.JFormattedTextField();
        endTime = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        startValue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        endValue = new javax.swing.JTextField();
        jDesktopPane10 = new javax.swing.JDesktopPane();
        jDesktopPane11 = new javax.swing.JDesktopPane();
        applyFilterButton = new javax.swing.JButton();
        resetFilterButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        flagButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("POI Detail");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Type");

        dataType.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        dataType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mold", "Air Quality" }));

        try {
            startTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        startTime.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        try {
            endTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        endTime.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Data Value");

        jLabel4.setText("Time&Date");

        jLabel5.setText("to");

        startValue.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel6.setText("to");

        endValue.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        applyFilterButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        applyFilterButton.setText("Apply Filter");
        applyFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFilterButtonActionPerformed(evt);
            }
        });

        resetFilterButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        resetFilterButton.setText("Reset Filter");
        resetFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFilterButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        backButton.setText("Back");
        backButton.setToolTipText("");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        flagButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        flagButton.setText("Flag");
        flagButton.setToolTipText("");
        flagButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        flagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane10)
            .addComponent(jDesktopPane11)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(applyFilterButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(flagButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetFilterButton)
                        .addGap(43, 43, 43))))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startTime, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(119, 119, 119))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startValue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(endValue, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dataType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(startValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(endValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(endTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applyFilterButton)
                    .addComponent(resetFilterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flagButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clean_up(){
       dataType.setSelectedIndex(0);
       startValue.setText("");
       endValue.setText("");
       startTime.setText("");
       endTime.setText("");
     
    }
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        frame.getContentPane().removeAll();
        frame.getContentPane().invalidate();
        frame.getContentPane().add(new City_Off_Func(frame));
        frame.getContentPane().revalidate();
        frame.pack();
    }//GEN-LAST:event_backButtonActionPerformed

    private void applyFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFilterButtonActionPerformed
        // TODO add your handling code here:
        String new_name = selected_location;
        String new_datatype = dataType.getSelectedItem().toString();
         int new_startvalue=0;
         int flag_tmp=1;
        if(!startValue.getText().equals("")){
            new_startvalue = Integer.parseInt(startValue.getText());
        }
        int new_endvalue=0;
        if(!endValue.getText().equals("")){
            new_endvalue= Integer.parseInt(endValue.getText());
        }
        String new_starttime =startTime.getText();
        String new_endtime =endTime.getText();
         if(new_starttime.equals("    -  -     :  ")){
             new_starttime=null;
         }
         if(new_endtime.equals("    -  -     :  ")){
             new_endtime=null;
         }
         System.out.println("new_starttime is " + new_starttime);
         System.out.println("new_endtime is "+new_endtime);
        boolean isDVEmpty=true;
        boolean isTimeEmpty=true;
        //System.out.println(new_startDate==null);
        if((new_startvalue!=0&& new_endvalue==0)||(new_startvalue==0 && new_endvalue!=0)){
            JOptionPane.showMessageDialog(null, "Please enter both the start value and the end value!");
            this.clean_up();
            flag_tmp=0;
        }else if(new_startvalue==0 && new_endvalue==0){
            isDVEmpty = true;
        }else{
            isDVEmpty=false;
        }
        if((new_starttime!=null&& new_endtime==null)||(new_starttime==null && new_endtime!=null)){
            JOptionPane.showMessageDialog(null, "Please enter both the start time and the end time!");
            this.clean_up();
            flag_tmp=0;
        }else if(new_starttime==null && new_endtime==null){
            isTimeEmpty = true;
        }else{
            isTimeEmpty=false;
        }
        System.out.println(isTimeEmpty);
        // public DataPoint(String name,String DateRecorded,int DataValue, String DataType, Boolean Accepted)
        if(flag_tmp==1){
        DataPoint dp_tmp = new DataPoint(new_name,new_starttime,new_startvalue,new_datatype,true);
        try{
       dp_table=DB_test.View_POI_datapoint (dp_tmp,new_endtime, new_endvalue, isTimeEmpty, isDVEmpty);
        table = new myTable(dp_table,column,this,new int[]{60,320,500,100});
        this.table.table.repaint();
        }
        catch(SQLException se){
             System.out.println("SQLException in POI_detail");
           }}
        flag=1;
    }//GEN-LAST:event_applyFilterButtonActionPerformed

    private void resetFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFilterButtonActionPerformed
        // TODO add your handling code here:
         this.clean_up();
         if(flag==1){
       this.table.table.setVisible(false);
         }
    }//GEN-LAST:event_resetFilterButtonActionPerformed

    private void flagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flagButtonActionPerformed
        // TODO add your handling code here:
        DB_test.FlagToggle(selected_location);
    }//GEN-LAST:event_flagButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyFilterButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox dataType;
    private javax.swing.JFormattedTextField endTime;
    private javax.swing.JTextField endValue;
    private javax.swing.JButton flagButton;
    private javax.swing.JDesktopPane jDesktopPane10;
    private javax.swing.JDesktopPane jDesktopPane11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton resetFilterButton;
    private javax.swing.JFormattedTextField startTime;
    private javax.swing.JTextField startValue;
    // End of variables declaration//GEN-END:variables
}
